2025-02-28 22:31:36.164 [main] INFO  a.conectores_hibernate.hmarort.Main - Iniciando aplicaci贸n de gesti贸n de pedidos
2025-02-28 22:31:36.168 [main] INFO  a.conectores_hibernate.hmarort.Main - Interfaz seleccionada: MANUAL
2025-02-28 22:31:36.169 [main] INFO  a.conectores_hibernate.hmarort.Main - Base de datos seleccionada: HIBERNATE
2025-02-28 22:31:36.173 [main] INFO  a.c.hmarort.utils.HibernateUtil - Inicializando SessionFactory de Hibernate
2025-02-28 22:31:36.259 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version 6.4.1.Final
2025-02-28 22:31:36.496 [main] INFO  o.h.c.i.RegionFactoryInitiator - HHH000026: Second-level cache disabled
2025-02-28 22:31:36.615 [main] WARN  o.hibernate.orm.connections.pooling - HHH10001002: Using built-in connection pool (not intended for production use)
2025-02-28 22:31:36.619 [main] INFO  o.hibernate.orm.connections.pooling - HHH10001005: Loaded JDBC driver class: org.sqlite.JDBC
2025-02-28 22:31:36.620 [main] INFO  o.hibernate.orm.connections.pooling - HHH10001012: Connecting with JDBC URL [jdbc:sqlite:src/main/resources/pedidos.db]
2025-02-28 22:31:36.620 [main] INFO  o.hibernate.orm.connections.pooling - HHH10001001: Connection properties: {}
2025-02-28 22:31:36.620 [main] INFO  o.hibernate.orm.connections.pooling - HHH10001003: Autocommit mode: false
2025-02-28 22:31:36.623 [main] INFO  o.hibernate.orm.connections.pooling - HHH10001115: Connection pool size: 20 (min=1)
2025-02-28 22:31:37.730 [main] INFO  o.hibernate.orm.connections.access - HHH10001501: Connection obtained from JdbcConnectionAccess [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess@5eb87338] for (non-JTA) DDL execution was not in auto-commit mode; the Connection 'local transaction' will be committed and the Connection will be set into auto-commit mode.
2025-02-28 22:31:37.745 [main] INFO  a.c.hmarort.utils.HibernateUtil - SessionFactory inicializada correctamente
2025-02-28 22:31:37.745 [main] INFO  a.c.h.d.HibernateConfig - Configuraci贸n de Hibernate inicializada
2025-02-28 22:31:37.749 [main] INFO  a.c.hmarort.utils.SessionManager - Inicializando SessionFactory de Hibernate
2025-02-28 22:31:37.771 [main] INFO  o.h.c.i.RegionFactoryInitiator - HHH000026: Second-level cache disabled
2025-02-28 22:31:37.777 [main] WARN  o.hibernate.orm.connections.pooling - HHH10001002: Using built-in connection pool (not intended for production use)
2025-02-28 22:31:37.778 [main] INFO  o.hibernate.orm.connections.pooling - HHH10001005: Loaded JDBC driver class: org.sqlite.JDBC
2025-02-28 22:31:37.778 [main] INFO  o.hibernate.orm.connections.pooling - HHH10001012: Connecting with JDBC URL [jdbc:sqlite:src/main/resources/pedidos.db]
2025-02-28 22:31:37.778 [main] INFO  o.hibernate.orm.connections.pooling - HHH10001001: Connection properties: {}
2025-02-28 22:31:37.779 [main] INFO  o.hibernate.orm.connections.pooling - HHH10001003: Autocommit mode: false
2025-02-28 22:31:37.779 [main] INFO  o.hibernate.orm.connections.pooling - HHH10001115: Connection pool size: 20 (min=1)
2025-02-28 22:31:37.838 [main] INFO  o.hibernate.orm.connections.access - HHH10001501: Connection obtained from JdbcConnectionAccess [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess@1c7f9861] for (non-JTA) DDL execution was not in auto-commit mode; the Connection 'local transaction' will be committed and the Connection will be set into auto-commit mode.
2025-02-28 22:31:37.842 [main] INFO  a.c.hmarort.utils.SessionManager - SessionFactory inicializada correctamente
2025-02-28 22:31:47.477 [main] ERROR a.c.h.d.i.hibernate.DAOClienteImpl - Error al buscar cliente por ID
org.hibernate.HibernateException: Calling method 'get' is not valid without an active transaction (Current status: NOT_ACTIVE)
	at org.hibernate.context.internal.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:339)
	at jdk.proxy2/jdk.proxy2.$Proxy53.get(Unknown Source)
	at ad.conectores_hibernate.hmarort.dao.implementacion.hibernate.DAOClienteImpl.obtenerClientePorId(DAOClienteImpl.java:52)
	at ad.conectores_hibernate.hmarort.ui.UIManualImpl.modificarCliente(UIManualImpl.java:153)
	at ad.conectores_hibernate.hmarort.ui.UIManualImpl.gestionarClientes(UIManualImpl.java:117)
	at ad.conectores_hibernate.hmarort.ui.UIManualImpl.iniciar(UIManualImpl.java:62)
	at ad.conectores_hibernate.hmarort.Main.main(Main.java:56)
2025-02-28 22:31:47.478 [main] ERROR a.c.hmarort.ui.UIManualImpl - Error en la interfaz manual
java.sql.SQLException: Error al buscar cliente: Calling method 'get' is not valid without an active transaction (Current status: NOT_ACTIVE)
	at ad.conectores_hibernate.hmarort.dao.implementacion.hibernate.DAOClienteImpl.obtenerClientePorId(DAOClienteImpl.java:61)
	at ad.conectores_hibernate.hmarort.ui.UIManualImpl.modificarCliente(UIManualImpl.java:153)
	at ad.conectores_hibernate.hmarort.ui.UIManualImpl.gestionarClientes(UIManualImpl.java:117)
	at ad.conectores_hibernate.hmarort.ui.UIManualImpl.iniciar(UIManualImpl.java:62)
	at ad.conectores_hibernate.hmarort.Main.main(Main.java:56)
Caused by: org.hibernate.HibernateException: Calling method 'get' is not valid without an active transaction (Current status: NOT_ACTIVE)
	at org.hibernate.context.internal.ThreadLocalSessionContext$TransactionProtectionWrapper.invoke(ThreadLocalSessionContext.java:339)
	at jdk.proxy2/jdk.proxy2.$Proxy53.get(Unknown Source)
	at ad.conectores_hibernate.hmarort.dao.implementacion.hibernate.DAOClienteImpl.obtenerClientePorId(DAOClienteImpl.java:52)
	... 4 common frames omitted
2025-02-28 22:32:02.547 [main] INFO  a.c.h.d.i.hibernate.DAOPedidoImpl - Pedido actualizado con ID: 2
2025-02-28 22:32:06.206 [main] INFO  a.conectores_hibernate.hmarort.Main - Aplicaci贸n finalizada exitosamente
